INSERT INTO books (id, title, author, stock, unit_price) VALUES (1, 'The Book Thief', 'Markus Zusak', 11, 21.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (2, 'The Book of Dragons', 'Edith Nesbit', 12, 22.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (3, 'The Foot Book', 'Dr. Seuss', 13, 23.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (4, 'The Jungle Book', 'Rudyard Kipling', 14, 24.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (5, 'The Graveyard Book', 'Neil Gaiman', 15, 20.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (6, 'Summary the Psychology of Money', 'Book PRO', 16, 21.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (7, 'The Book Of Three', 'Lloyd Alexander', 17, 22.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (8, 'After (After Series, Book 1)', 'Anna Todd', 18, 23.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (9, 'The Bachman Books (Long Walk / Rage / Roadwork / Running Man)', 'Stephen King', 19, 24.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (10, 'Childcraft', 'World Book', 10, 20.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (11, 'Eyewitness', 'DK Publishing', 11, 21.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (12, 'Stellaluna', 'Janell Cannon', 12, 22.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (13, 'Gorin no sho', 'Miyamoto Musashi', 13, 23.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (14, 'Doomsday book', 'Connie Willis', 14, 24.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (15, 'The Book of Tea', 'Okakura Kakuzō', 15, 20.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (16, 'Shatter Me', 'Tahereh Mafi', 16, 21.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (17, 'Game of Thrones', 'Book Of Thrones', 17, 22.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (18, 'The Complete Jungle Book', 'Rudyard Kipling', 18, 23.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (19, 'The Blade Itself', 'Joe Abercrombie', 19, 24.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (20, 'March. Book One', 'John Lewis', 10, 20.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (21, 'How to Read a Book', 'Mortimer J. Adler', 11, 21.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (22, 'The Intelligent Investor', 'Benjamin Graham', 12, 22.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (23, 'Sketch Book for Kids', 'Js Sketch Book', 13, 23.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (24, 'Dr. Seuss''s ABC', 'Dr. Seuss', 14, 24.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (25, 'The Case-Book of Sherlock Holmes', 'Arthur Conan Doyle', 15, 20.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (26, 'The Violet Fairy Book (Large Print)', 'Andrew Lang', 16, 21.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (27, 'Charlotte''s Web', 'Jennifer Frantz', 17, 22.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (28, 'Books of Blood Volume One', 'Clive Barker', 18, 23.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (29, 'The Book of Life', 'Deborah Harkness', 19, 24.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (30, 'Goodnight Moon', 'Margaret Wise Brown', 10, 20.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (31, 'Storm Front', 'Jim Butcher', 11, 21.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (32, 'Demon Slayer Coloring Book', 'sara coloring', 12, 22.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (33, 'The Second Jungle Book', 'Rudyard Kipling', 13, 23.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (34, 'The Calvin and Hobbes tenth anniversary book', 'Bill Watterson', 14, 24.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (35, 'The Gruffalo', 'Julia Donaldson', 15, 20.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (36, 'The Green Fairy Book', 'Andrew Lang', 16, 21.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (37, 'Wacky Wednesday', 'Dr. Seuss', 17, 22.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (38, 'Amulet', 'Kazu Kibuishi', 18, 23.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (39, 'Gardens of the Moon', 'Steven Erikson', 19, 24.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (40, 'Book Lovers', 'Emily Henry', 10, 20.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (41, 'Read People Like a Book', 'Patrick King', 11, 21.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (42, 'We Are in a Book! (Elephant & Piggie)', 'Mo Willems', 12, 22.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (43, 'The Code Book', 'Simon Singh', 13, 23.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (44, 'Yellowface', 'R. F. Kuang', 14, 24.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (45, 'The Monster at the End of This Book', 'Jon Stone', 15, 20.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (46, 'A Wonder Book for Girls and Boys', 'Nathaniel Hawthorne', 16, 21.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (47, 'How to Read a Book', 'Mortimer J. Adler', 17, 22.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (48, 'Paradise Lost', 'John Milton', 18, 23.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (49, 'The Blue Fairy Book', 'Andrew Lang', 19, 24.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (50, 'The Book with No Pictures', 'B. J. Novak', 10, 20.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (51, 'Lightlark', 'Alex Aster', 11, 21.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (52, 'A book', 'Desi Arnaz', 12, 22.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (53, 'Eragon', 'Christopher Paolini', 13, 23.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (54, 'Everything is F*cked', 'Mark Manson', 14, 24.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (55, 'The Comfort Book', 'Matt Haig', 15, 20.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (56, 'Madeleine', 'Ludwig Bemelmans', 16, 21.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (57, 'Superfudge', 'Judy Blume', 17, 22.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (58, 'The City of Ember (The First Book of Ember)', 'Jeanne DuPrau', 18, 23.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (59, 'The Magic in the Weaving', 'Tamora Pierce', 19, 24.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (60, 'The mitten', 'Jan Brett', 10, 20.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (61, 'A Little Black Book', 'Graeme Jenkinson', 11, 21.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (62, 'Sula', 'Toni Morrison', 12, 22.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (63, 'Dr. Seuss''s sleep book', 'Dr. Seuss', 13, 23.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (64, 'Complete book of witchcraft', 'Raymond Buckland', 14, 24.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (65, 'Cress', 'Marissa Meyer', 15, 20.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (66, 'Words of Radiance', 'Brandon Sanderson', 16, 21.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (67, 'Fox in Socks', 'Dr. Seuss', 17, 22.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (68, 'City of Glass', 'Cassandra Clare', 18, 23.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (69, 'The Rudest Book Ever', 'Shwetabh Gangwar', 19, 24.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (70, 'Memories of ice', 'Steven Erikson', 10, 20.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (71, 'Marked', 'P. C. Cast', 11, 21.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (72, 'The Complete Book of Magic and Witchcraft', 'Kathryn Paulsen', 12, 22.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (73, 'Babylon’s ashes', 'James S. A. Corey', 13, 23.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (74, 'Dean Koontz''s Frankenstein', 'Dean Koontz', 14, 24.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (75, 'Magician''s Gambit (The Belgariad, Book 3)', 'David Eddings', 15, 20.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (76, 'The Book of Lost Tales [1/2]', 'J.R.R. Tolkien', 16, 21.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (77, 'Go, Dog. Go!', 'P. D. Eastman', 17, 22.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (78, 'The Book', 'Hungry Minds', 18, 23.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (79, 'Ignite Me', 'Tahereh Mafi', 19, 24.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (80, 'Unwind', 'Neal Shusterman', 10, 20.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (81, 'Beautiful Creatures (Beautiful Creatures Series, Book 1)', 'Kami Garcia', 11, 21.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (82, 'Scarlet', 'Marissa Meyer', 12, 22.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (83, 'The Pink Fairy Book', 'Andrew Lang', 13, 23.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (84, 'Shapes in the Sky', 'Josepha Sherman', 14, 24.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (85, 'The book of answers', 'Carol Bolt', 15, 20.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (86, 'Dead Beat (The Dresden Files, Book 7)', 'Jim Butcher', 16, 21.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (87, 'The Library Book', 'Susan Orlean', 17, 22.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (88, 'The Ruins of Gorlan', 'John Flanagan', 18, 23.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (89, 'The Blue Sword', 'Robin McKinley', 19, 24.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (90, 'The Book of the Dead', 'E. A. Wallis Budge', 10, 20.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (91, 'Mildred and Sam', 'Sharleen Collicott', 11, 21.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (92, 'Briar''s book', 'Tamora Pierce', 12, 22.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (93, 'Frederica', 'Georgette Heyer', 13, 23.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (94, 'The Grey Fairy Book', 'Andrew Lang', 14, 24.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (95, 'Hop on Pop', 'Dr. Seuss', 15, 20.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (96, 'The Fires of Heaven', 'Robert Jordan', 16, 21.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (97, 'Little Bear', 'Else Holmelund Minarik', 17, 22.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (98, 'After We Collided (After Series, Book 2)', 'Anna Todd', 18, 23.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (99, 'Bonehunters', 'Steven Erikson', 19, 24.0);
INSERT INTO books (id, title, author, stock, unit_price) VALUES (100, 'The Lilac Fairy Book', 'Andrew Lang', 10, 20.0);
